development:
  adapter: postgresql
  encoding: unicode
  database: auth_dev
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: auth_test
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: auth_prod
  username: postgres
  password: postgres